// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_handoffs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cancelHandoff = `-- name: CancelHandoff :one
UPDATE agent_handoffs SET
  status = 'cancelled',
  failure_reason = ?1,
  completed_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?2 AND status IN ('pending', 'dispatched', 'running')
RETURNING id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at
`

type CancelHandoffParams struct {
	FailureReason string `json:"failure_reason"`
	ID            string `json:"id"`
}

func (q *Queries) CancelHandoff(ctx context.Context, arg CancelHandoffParams) (AgentHandoff, error) {
	row := q.db.QueryRowContext(ctx, cancelHandoff, arg.FailureReason, arg.ID)
	var i AgentHandoff
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.IssueID,
		&i.FromActorType,
		&i.FromBotID,
		&i.FromUserID,
		&i.ToBotID,
		&i.TriggerCommentID,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ResultCommentID,
		&i.ReturnHandoffID,
		&i.Status,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeHandoff = `-- name: CompleteHandoff :one
UPDATE agent_handoffs SET
  status = 'completed',
  result_comment_id = ?1,
  completed_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?2 AND status IN ('pending', 'dispatched', 'running')
RETURNING id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at
`

type CompleteHandoffParams struct {
	ResultCommentID sql.NullString `json:"result_comment_id"`
	ID              string         `json:"id"`
}

func (q *Queries) CompleteHandoff(ctx context.Context, arg CompleteHandoffParams) (AgentHandoff, error) {
	row := q.db.QueryRowContext(ctx, completeHandoff, arg.ResultCommentID, arg.ID)
	var i AgentHandoff
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.IssueID,
		&i.FromActorType,
		&i.FromBotID,
		&i.FromUserID,
		&i.ToBotID,
		&i.TriggerCommentID,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ResultCommentID,
		&i.ReturnHandoffID,
		&i.Status,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAgentHandoff = `-- name: CreateAgentHandoff :one
INSERT INTO agent_handoffs (
  id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id,
  to_bot_id, trigger_comment_id, source_session_id, target_session_id,
  status, metadata
) VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11
)
RETURNING id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at
`

type CreateAgentHandoffParams struct {
	TeamID           string         `json:"team_id"`
	IssueID          sql.NullString `json:"issue_id"`
	FromActorType    string         `json:"from_actor_type"`
	FromBotID        sql.NullString `json:"from_bot_id"`
	FromUserID       sql.NullString `json:"from_user_id"`
	ToBotID          string         `json:"to_bot_id"`
	TriggerCommentID sql.NullString `json:"trigger_comment_id"`
	SourceSessionID  sql.NullString `json:"source_session_id"`
	TargetSessionID  sql.NullString `json:"target_session_id"`
	Status           string         `json:"status"`
	Metadata         string         `json:"metadata"`
}

func (q *Queries) CreateAgentHandoff(ctx context.Context, arg CreateAgentHandoffParams) (AgentHandoff, error) {
	row := q.db.QueryRowContext(ctx, createAgentHandoff,
		arg.TeamID,
		arg.IssueID,
		arg.FromActorType,
		arg.FromBotID,
		arg.FromUserID,
		arg.ToBotID,
		arg.TriggerCommentID,
		arg.SourceSessionID,
		arg.TargetSessionID,
		arg.Status,
		arg.Metadata,
	)
	var i AgentHandoff
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.IssueID,
		&i.FromActorType,
		&i.FromBotID,
		&i.FromUserID,
		&i.ToBotID,
		&i.TriggerCommentID,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ResultCommentID,
		&i.ReturnHandoffID,
		&i.Status,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failHandoff = `-- name: FailHandoff :one
UPDATE agent_handoffs SET
  status = 'failed',
  failure_reason = ?1,
  completed_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?2 AND status IN ('pending', 'dispatched', 'running')
RETURNING id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at
`

type FailHandoffParams struct {
	FailureReason string `json:"failure_reason"`
	ID            string `json:"id"`
}

func (q *Queries) FailHandoff(ctx context.Context, arg FailHandoffParams) (AgentHandoff, error) {
	row := q.db.QueryRowContext(ctx, failHandoff, arg.FailureReason, arg.ID)
	var i AgentHandoff
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.IssueID,
		&i.FromActorType,
		&i.FromBotID,
		&i.FromUserID,
		&i.ToBotID,
		&i.TriggerCommentID,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ResultCommentID,
		&i.ReturnHandoffID,
		&i.Status,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAgentHandoff = `-- name: GetAgentHandoff :one
SELECT id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at FROM agent_handoffs WHERE id = ?1
`

func (q *Queries) GetAgentHandoff(ctx context.Context, id string) (AgentHandoff, error) {
	row := q.db.QueryRowContext(ctx, getAgentHandoff, id)
	var i AgentHandoff
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.IssueID,
		&i.FromActorType,
		&i.FromBotID,
		&i.FromUserID,
		&i.ToBotID,
		&i.TriggerCommentID,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ResultCommentID,
		&i.ReturnHandoffID,
		&i.Status,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listHandoffsByIssue = `-- name: ListHandoffsByIssue :many
SELECT id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at FROM agent_handoffs
WHERE issue_id = ?1
ORDER BY created_at ASC
`

func (q *Queries) ListHandoffsByIssue(ctx context.Context, issueID sql.NullString) ([]AgentHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listHandoffsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHandoff
	for rows.Next() {
		var i AgentHandoff
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.IssueID,
			&i.FromActorType,
			&i.FromBotID,
			&i.FromUserID,
			&i.ToBotID,
			&i.TriggerCommentID,
			&i.SourceSessionID,
			&i.TargetSessionID,
			&i.ResultCommentID,
			&i.ReturnHandoffID,
			&i.Status,
			&i.FailureReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHandoffsToBot = `-- name: ListPendingHandoffsToBot :many
SELECT id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at FROM agent_handoffs
WHERE to_bot_id = ?1
  AND status IN ('pending', 'dispatched', 'running')
ORDER BY created_at ASC
`

func (q *Queries) ListPendingHandoffsToBot(ctx context.Context, toBotID string) ([]AgentHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listPendingHandoffsToBot, toBotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHandoff
	for rows.Next() {
		var i AgentHandoff
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.IssueID,
			&i.FromActorType,
			&i.FromBotID,
			&i.FromUserID,
			&i.ToBotID,
			&i.TriggerCommentID,
			&i.SourceSessionID,
			&i.TargetSessionID,
			&i.ResultCommentID,
			&i.ReturnHandoffID,
			&i.Status,
			&i.FailureReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHandoffsToBotForIssue = `-- name: ListPendingHandoffsToBotForIssue :many
SELECT id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at FROM agent_handoffs
WHERE to_bot_id = ?1
  AND issue_id = ?2
  AND status IN ('pending', 'dispatched', 'running')
ORDER BY created_at DESC
`

type ListPendingHandoffsToBotForIssueParams struct {
	ToBotID string         `json:"to_bot_id"`
	IssueID sql.NullString `json:"issue_id"`
}

func (q *Queries) ListPendingHandoffsToBotForIssue(ctx context.Context, arg ListPendingHandoffsToBotForIssueParams) ([]AgentHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listPendingHandoffsToBotForIssue, arg.ToBotID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHandoff
	for rows.Next() {
		var i AgentHandoff
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.IssueID,
			&i.FromActorType,
			&i.FromBotID,
			&i.FromUserID,
			&i.ToBotID,
			&i.TriggerCommentID,
			&i.SourceSessionID,
			&i.TargetSessionID,
			&i.ResultCommentID,
			&i.ReturnHandoffID,
			&i.Status,
			&i.FailureReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReturnsForBotInIssue = `-- name: ListPendingReturnsForBotInIssue :many
SELECT id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at FROM agent_handoffs
WHERE from_bot_id = ?1
  AND issue_id = ?2
  AND status = 'completed'
  AND return_handoff_id IS NULL
ORDER BY completed_at ASC
`

type ListPendingReturnsForBotInIssueParams struct {
	FromBotID sql.NullString `json:"from_bot_id"`
	IssueID   sql.NullString `json:"issue_id"`
}

func (q *Queries) ListPendingReturnsForBotInIssue(ctx context.Context, arg ListPendingReturnsForBotInIssueParams) ([]AgentHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReturnsForBotInIssue, arg.FromBotID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHandoff
	for rows.Next() {
		var i AgentHandoff
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.IssueID,
			&i.FromActorType,
			&i.FromBotID,
			&i.FromUserID,
			&i.ToBotID,
			&i.TriggerCommentID,
			&i.SourceSessionID,
			&i.TargetSessionID,
			&i.ResultCommentID,
			&i.ReturnHandoffID,
			&i.Status,
			&i.FailureReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHandoffDispatched = `-- name: MarkHandoffDispatched :one
UPDATE agent_handoffs SET
  status = 'dispatched',
  target_session_id = COALESCE(?1, target_session_id),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?2 AND status = 'pending'
RETURNING id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at
`

type MarkHandoffDispatchedParams struct {
	TargetSessionID sql.NullString `json:"target_session_id"`
	ID              string         `json:"id"`
}

func (q *Queries) MarkHandoffDispatched(ctx context.Context, arg MarkHandoffDispatchedParams) (AgentHandoff, error) {
	row := q.db.QueryRowContext(ctx, markHandoffDispatched, arg.TargetSessionID, arg.ID)
	var i AgentHandoff
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.IssueID,
		&i.FromActorType,
		&i.FromBotID,
		&i.FromUserID,
		&i.ToBotID,
		&i.TriggerCommentID,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ResultCommentID,
		&i.ReturnHandoffID,
		&i.Status,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markHandoffRunning = `-- name: MarkHandoffRunning :one
UPDATE agent_handoffs SET
  status = 'running',
  target_session_id = COALESCE(?1, target_session_id),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?2 AND status IN ('pending', 'dispatched')
RETURNING id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at
`

type MarkHandoffRunningParams struct {
	TargetSessionID sql.NullString `json:"target_session_id"`
	ID              string         `json:"id"`
}

func (q *Queries) MarkHandoffRunning(ctx context.Context, arg MarkHandoffRunningParams) (AgentHandoff, error) {
	row := q.db.QueryRowContext(ctx, markHandoffRunning, arg.TargetSessionID, arg.ID)
	var i AgentHandoff
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.IssueID,
		&i.FromActorType,
		&i.FromBotID,
		&i.FromUserID,
		&i.ToBotID,
		&i.TriggerCommentID,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ResultCommentID,
		&i.ReturnHandoffID,
		&i.Status,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setHandoffReturn = `-- name: SetHandoffReturn :one
UPDATE agent_handoffs SET
  return_handoff_id = ?1,
  status = 'returned',
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?2 AND status IN ('completed', 'returned')
RETURNING id, team_id, issue_id, from_actor_type, from_bot_id, from_user_id, to_bot_id, trigger_comment_id, source_session_id, target_session_id, result_comment_id, return_handoff_id, status, failure_reason, metadata, created_at, updated_at, completed_at
`

type SetHandoffReturnParams struct {
	ReturnHandoffID sql.NullString `json:"return_handoff_id"`
	ID              string         `json:"id"`
}

func (q *Queries) SetHandoffReturn(ctx context.Context, arg SetHandoffReturnParams) (AgentHandoff, error) {
	row := q.db.QueryRowContext(ctx, setHandoffReturn, arg.ReturnHandoffID, arg.ID)
	var i AgentHandoff
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.IssueID,
		&i.FromActorType,
		&i.FromBotID,
		&i.FromUserID,
		&i.ToBotID,
		&i.TriggerCommentID,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ResultCommentID,
		&i.ReturnHandoffID,
		&i.Status,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
