// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_file_locks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const acquireTeamFileLock = `-- name: AcquireTeamFileLock :one
INSERT INTO team_file_locks (
  id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id,
  issue_id, session_id, handoff_id, expires_at, metadata
) VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11
)
ON CONFLICT (team_id, path, scope) DO NOTHING
RETURNING id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata
`

type AcquireTeamFileLockParams struct {
	TeamID      string         `json:"team_id"`
	Path        string         `json:"path"`
	Scope       string         `json:"scope"`
	OwnerType   string         `json:"owner_type"`
	OwnerBotID  sql.NullString `json:"owner_bot_id"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	IssueID     sql.NullString `json:"issue_id"`
	SessionID   sql.NullString `json:"session_id"`
	HandoffID   sql.NullString `json:"handoff_id"`
	ExpiresAt   string         `json:"expires_at"`
	Metadata    string         `json:"metadata"`
}

func (q *Queries) AcquireTeamFileLock(ctx context.Context, arg AcquireTeamFileLockParams) (TeamFileLock, error) {
	row := q.db.QueryRowContext(ctx, acquireTeamFileLock,
		arg.TeamID,
		arg.Path,
		arg.Scope,
		arg.OwnerType,
		arg.OwnerBotID,
		arg.OwnerUserID,
		arg.IssueID,
		arg.SessionID,
		arg.HandoffID,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i TeamFileLock
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.Scope,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerUserID,
		&i.IssueID,
		&i.SessionID,
		&i.HandoffID,
		&i.AcquiredAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const getTeamFileLock = `-- name: GetTeamFileLock :one
SELECT id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata FROM team_file_locks
WHERE team_id = ?1 AND path = ?2 AND scope = ?3
`

type GetTeamFileLockParams struct {
	TeamID string `json:"team_id"`
	Path   string `json:"path"`
	Scope  string `json:"scope"`
}

func (q *Queries) GetTeamFileLock(ctx context.Context, arg GetTeamFileLockParams) (TeamFileLock, error) {
	row := q.db.QueryRowContext(ctx, getTeamFileLock, arg.TeamID, arg.Path, arg.Scope)
	var i TeamFileLock
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.Scope,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerUserID,
		&i.IssueID,
		&i.SessionID,
		&i.HandoffID,
		&i.AcquiredAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const getTeamFileLockByID = `-- name: GetTeamFileLockByID :one
SELECT id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata FROM team_file_locks WHERE id = ?1
`

func (q *Queries) GetTeamFileLockByID(ctx context.Context, id string) (TeamFileLock, error) {
	row := q.db.QueryRowContext(ctx, getTeamFileLockByID, id)
	var i TeamFileLock
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.Scope,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerUserID,
		&i.IssueID,
		&i.SessionID,
		&i.HandoffID,
		&i.AcquiredAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const listActiveTeamFileLocks = `-- name: ListActiveTeamFileLocks :many
SELECT id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata FROM team_file_locks
WHERE team_id = ?1
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY acquired_at DESC
`

func (q *Queries) ListActiveTeamFileLocks(ctx context.Context, teamID string) ([]TeamFileLock, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTeamFileLocks, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamFileLock
	for rows.Next() {
		var i TeamFileLock
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Path,
			&i.Scope,
			&i.OwnerType,
			&i.OwnerBotID,
			&i.OwnerUserID,
			&i.IssueID,
			&i.SessionID,
			&i.HandoffID,
			&i.AcquiredAt,
			&i.RefreshedAt,
			&i.ExpiresAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamFileLocks = `-- name: ListTeamFileLocks :many
SELECT id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata FROM team_file_locks
WHERE team_id = ?1
ORDER BY acquired_at DESC
`

func (q *Queries) ListTeamFileLocks(ctx context.Context, teamID string) ([]TeamFileLock, error) {
	rows, err := q.db.QueryContext(ctx, listTeamFileLocks, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamFileLock
	for rows.Next() {
		var i TeamFileLock
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Path,
			&i.Scope,
			&i.OwnerType,
			&i.OwnerBotID,
			&i.OwnerUserID,
			&i.IssueID,
			&i.SessionID,
			&i.HandoffID,
			&i.AcquiredAt,
			&i.RefreshedAt,
			&i.ExpiresAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTeamFileLock = `-- name: RefreshTeamFileLock :one
UPDATE team_file_locks SET
  refreshed_at = CURRENT_TIMESTAMP,
  expires_at = ?1
WHERE id = ?2
RETURNING id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata
`

type RefreshTeamFileLockParams struct {
	ExpiresAt string `json:"expires_at"`
	ID        string `json:"id"`
}

func (q *Queries) RefreshTeamFileLock(ctx context.Context, arg RefreshTeamFileLockParams) (TeamFileLock, error) {
	row := q.db.QueryRowContext(ctx, refreshTeamFileLock, arg.ExpiresAt, arg.ID)
	var i TeamFileLock
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.Scope,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerUserID,
		&i.IssueID,
		&i.SessionID,
		&i.HandoffID,
		&i.AcquiredAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const releaseExpiredTeamFileLocks = `-- name: ReleaseExpiredTeamFileLocks :exec
DELETE FROM team_file_locks
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) ReleaseExpiredTeamFileLocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, releaseExpiredTeamFileLocks)
	return err
}

const releaseTeamFileLock = `-- name: ReleaseTeamFileLock :exec
DELETE FROM team_file_locks WHERE id = ?1
`

func (q *Queries) ReleaseTeamFileLock(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, releaseTeamFileLock, id)
	return err
}
