// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_issues.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTeamIssue = `-- name: CreateTeamIssue :one
INSERT INTO team_issues (
  id, team_id, number, title, description, status,
  assignee_type, assignee_bot_id, assignee_user_id,
  created_by_type, created_by_bot_id, created_by_user_id,
  parent_issue_id, metadata
) VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  (SELECT COALESCE(MAX(number), 0) + 1 FROM team_issues WHERE team_id = ?1),
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12
)
RETURNING id, team_id, number, title, description, status, assignee_type, assignee_bot_id, assignee_user_id, created_by_type, created_by_bot_id, created_by_user_id, parent_issue_id, metadata, closed_at, created_at, updated_at
`

type CreateTeamIssueParams struct {
	TeamID          string         `json:"team_id"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	Status          string         `json:"status"`
	AssigneeType    sql.NullString `json:"assignee_type"`
	AssigneeBotID   sql.NullString `json:"assignee_bot_id"`
	AssigneeUserID  sql.NullString `json:"assignee_user_id"`
	CreatedByType   string         `json:"created_by_type"`
	CreatedByBotID  sql.NullString `json:"created_by_bot_id"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
	ParentIssueID   sql.NullString `json:"parent_issue_id"`
	Metadata        string         `json:"metadata"`
}

func (q *Queries) CreateTeamIssue(ctx context.Context, arg CreateTeamIssueParams) (TeamIssue, error) {
	row := q.db.QueryRowContext(ctx, createTeamIssue,
		arg.TeamID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeType,
		arg.AssigneeBotID,
		arg.AssigneeUserID,
		arg.CreatedByType,
		arg.CreatedByBotID,
		arg.CreatedByUserID,
		arg.ParentIssueID,
		arg.Metadata,
	)
	var i TeamIssue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeType,
		&i.AssigneeBotID,
		&i.AssigneeUserID,
		&i.CreatedByType,
		&i.CreatedByBotID,
		&i.CreatedByUserID,
		&i.ParentIssueID,
		&i.Metadata,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamIssueComment = `-- name: CreateTeamIssueComment :one
INSERT INTO team_issue_comments (
  id, issue_id, team_id, parent_comment_id, author_type,
  author_bot_id, author_user_id, content, metadata
) VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING id, issue_id, team_id, parent_comment_id, author_type, author_bot_id, author_user_id, content, metadata, created_at, updated_at
`

type CreateTeamIssueCommentParams struct {
	IssueID         string         `json:"issue_id"`
	TeamID          string         `json:"team_id"`
	ParentCommentID sql.NullString `json:"parent_comment_id"`
	AuthorType      string         `json:"author_type"`
	AuthorBotID     sql.NullString `json:"author_bot_id"`
	AuthorUserID    sql.NullString `json:"author_user_id"`
	Content         string         `json:"content"`
	Metadata        string         `json:"metadata"`
}

func (q *Queries) CreateTeamIssueComment(ctx context.Context, arg CreateTeamIssueCommentParams) (TeamIssueComment, error) {
	row := q.db.QueryRowContext(ctx, createTeamIssueComment,
		arg.IssueID,
		arg.TeamID,
		arg.ParentCommentID,
		arg.AuthorType,
		arg.AuthorBotID,
		arg.AuthorUserID,
		arg.Content,
		arg.Metadata,
	)
	var i TeamIssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.TeamID,
		&i.ParentCommentID,
		&i.AuthorType,
		&i.AuthorBotID,
		&i.AuthorUserID,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeamIssue = `-- name: DeleteTeamIssue :exec
DELETE FROM team_issues WHERE id = ?1
`

func (q *Queries) DeleteTeamIssue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTeamIssue, id)
	return err
}

const deleteTeamIssueComment = `-- name: DeleteTeamIssueComment :exec
DELETE FROM team_issue_comments WHERE id = ?1
`

func (q *Queries) DeleteTeamIssueComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTeamIssueComment, id)
	return err
}

const getTeamIssue = `-- name: GetTeamIssue :one
SELECT id, team_id, number, title, description, status, assignee_type, assignee_bot_id, assignee_user_id, created_by_type, created_by_bot_id, created_by_user_id, parent_issue_id, metadata, closed_at, created_at, updated_at FROM team_issues WHERE id = ?1
`

func (q *Queries) GetTeamIssue(ctx context.Context, id string) (TeamIssue, error) {
	row := q.db.QueryRowContext(ctx, getTeamIssue, id)
	var i TeamIssue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeType,
		&i.AssigneeBotID,
		&i.AssigneeUserID,
		&i.CreatedByType,
		&i.CreatedByBotID,
		&i.CreatedByUserID,
		&i.ParentIssueID,
		&i.Metadata,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamIssueComment = `-- name: GetTeamIssueComment :one
SELECT id, issue_id, team_id, parent_comment_id, author_type, author_bot_id, author_user_id, content, metadata, created_at, updated_at FROM team_issue_comments WHERE id = ?1
`

func (q *Queries) GetTeamIssueComment(ctx context.Context, id string) (TeamIssueComment, error) {
	row := q.db.QueryRowContext(ctx, getTeamIssueComment, id)
	var i TeamIssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.TeamID,
		&i.ParentCommentID,
		&i.AuthorType,
		&i.AuthorBotID,
		&i.AuthorUserID,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamIssueInTeam = `-- name: GetTeamIssueInTeam :one
SELECT id, team_id, number, title, description, status, assignee_type, assignee_bot_id, assignee_user_id, created_by_type, created_by_bot_id, created_by_user_id, parent_issue_id, metadata, closed_at, created_at, updated_at FROM team_issues
WHERE id = ?1 AND team_id = ?2
`

type GetTeamIssueInTeamParams struct {
	ID     string `json:"id"`
	TeamID string `json:"team_id"`
}

func (q *Queries) GetTeamIssueInTeam(ctx context.Context, arg GetTeamIssueInTeamParams) (TeamIssue, error) {
	row := q.db.QueryRowContext(ctx, getTeamIssueInTeam, arg.ID, arg.TeamID)
	var i TeamIssue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeType,
		&i.AssigneeBotID,
		&i.AssigneeUserID,
		&i.CreatedByType,
		&i.CreatedByBotID,
		&i.CreatedByUserID,
		&i.ParentIssueID,
		&i.Metadata,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenTeamIssuesByTeam = `-- name: ListOpenTeamIssuesByTeam :many
SELECT id, team_id, number, title, description, status, assignee_type, assignee_bot_id, assignee_user_id, created_by_type, created_by_bot_id, created_by_user_id, parent_issue_id, metadata, closed_at, created_at, updated_at FROM team_issues
WHERE team_id = ?1
  AND status NOT IN ('done', 'cancelled')
ORDER BY updated_at DESC
`

func (q *Queries) ListOpenTeamIssuesByTeam(ctx context.Context, teamID string) ([]TeamIssue, error) {
	rows, err := q.db.QueryContext(ctx, listOpenTeamIssuesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamIssue
	for rows.Next() {
		var i TeamIssue
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeType,
			&i.AssigneeBotID,
			&i.AssigneeUserID,
			&i.CreatedByType,
			&i.CreatedByBotID,
			&i.CreatedByUserID,
			&i.ParentIssueID,
			&i.Metadata,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamIssueComments = `-- name: ListTeamIssueComments :many
SELECT id, issue_id, team_id, parent_comment_id, author_type, author_bot_id, author_user_id, content, metadata, created_at, updated_at FROM team_issue_comments
WHERE issue_id = ?1
ORDER BY created_at ASC
`

func (q *Queries) ListTeamIssueComments(ctx context.Context, issueID string) ([]TeamIssueComment, error) {
	rows, err := q.db.QueryContext(ctx, listTeamIssueComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamIssueComment
	for rows.Next() {
		var i TeamIssueComment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.TeamID,
			&i.ParentCommentID,
			&i.AuthorType,
			&i.AuthorBotID,
			&i.AuthorUserID,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamIssuesByTeam = `-- name: ListTeamIssuesByTeam :many
SELECT id, team_id, number, title, description, status, assignee_type, assignee_bot_id, assignee_user_id, created_by_type, created_by_bot_id, created_by_user_id, parent_issue_id, metadata, closed_at, created_at, updated_at FROM team_issues
WHERE team_id = ?1
ORDER BY updated_at DESC
`

func (q *Queries) ListTeamIssuesByTeam(ctx context.Context, teamID string) ([]TeamIssue, error) {
	rows, err := q.db.QueryContext(ctx, listTeamIssuesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamIssue
	for rows.Next() {
		var i TeamIssue
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeType,
			&i.AssigneeBotID,
			&i.AssigneeUserID,
			&i.CreatedByType,
			&i.CreatedByBotID,
			&i.CreatedByUserID,
			&i.ParentIssueID,
			&i.Metadata,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamIssuesForOwner = `-- name: ListTeamIssuesForOwner :many
SELECT i.id, i.team_id, i.number, i.title, i.description, i.status, i.assignee_type, i.assignee_bot_id, i.assignee_user_id, i.created_by_type, i.created_by_bot_id, i.created_by_user_id, i.parent_issue_id, i.metadata, i.closed_at, i.created_at, i.updated_at FROM team_issues i
JOIN agent_teams t ON t.id = i.team_id
WHERE t.owner_user_id = ?1
ORDER BY i.updated_at DESC
`

func (q *Queries) ListTeamIssuesForOwner(ctx context.Context, ownerUserID string) ([]TeamIssue, error) {
	rows, err := q.db.QueryContext(ctx, listTeamIssuesForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamIssue
	for rows.Next() {
		var i TeamIssue
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeType,
			&i.AssigneeBotID,
			&i.AssigneeUserID,
			&i.CreatedByType,
			&i.CreatedByBotID,
			&i.CreatedByUserID,
			&i.ParentIssueID,
			&i.Metadata,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamIssueAssignee = `-- name: SetTeamIssueAssignee :one
UPDATE team_issues SET
  assignee_type = ?1,
  assignee_bot_id = ?2,
  assignee_user_id = ?3,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?4
RETURNING id, team_id, number, title, description, status, assignee_type, assignee_bot_id, assignee_user_id, created_by_type, created_by_bot_id, created_by_user_id, parent_issue_id, metadata, closed_at, created_at, updated_at
`

type SetTeamIssueAssigneeParams struct {
	AssigneeType   sql.NullString `json:"assignee_type"`
	AssigneeBotID  sql.NullString `json:"assignee_bot_id"`
	AssigneeUserID sql.NullString `json:"assignee_user_id"`
	ID             string         `json:"id"`
}

func (q *Queries) SetTeamIssueAssignee(ctx context.Context, arg SetTeamIssueAssigneeParams) (TeamIssue, error) {
	row := q.db.QueryRowContext(ctx, setTeamIssueAssignee,
		arg.AssigneeType,
		arg.AssigneeBotID,
		arg.AssigneeUserID,
		arg.ID,
	)
	var i TeamIssue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeType,
		&i.AssigneeBotID,
		&i.AssigneeUserID,
		&i.CreatedByType,
		&i.CreatedByBotID,
		&i.CreatedByUserID,
		&i.ParentIssueID,
		&i.Metadata,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchTeamIssueAfterComment = `-- name: TouchTeamIssueAfterComment :exec
UPDATE team_issues SET updated_at = CURRENT_TIMESTAMP WHERE id = ?1
`

func (q *Queries) TouchTeamIssueAfterComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchTeamIssueAfterComment, id)
	return err
}

const updateTeamIssue = `-- name: UpdateTeamIssue :one
UPDATE team_issues SET
  title = COALESCE(?1, title),
  description = COALESCE(?2, description),
  status = COALESCE(?3, status),
  assignee_type = COALESCE(?4, assignee_type),
  assignee_bot_id = COALESCE(?5, assignee_bot_id),
  assignee_user_id = COALESCE(?6, assignee_user_id),
  metadata = COALESCE(?7, metadata),
  closed_at = CASE
    WHEN sqlc.narg(status) IN ('done', 'cancelled') AND closed_at IS NULL THEN CURRENT_TIMESTAMP
    WHEN ?3 IS NOT NULL AND sqlc.narg(status) NOT IN ('done', 'cancelled') THEN NULL
    ELSE closed_at
  END,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?8
RETURNING id, team_id, number, title, description, status, assignee_type, assignee_bot_id, assignee_user_id, created_by_type, created_by_bot_id, created_by_user_id, parent_issue_id, metadata, closed_at, created_at, updated_at
`

type UpdateTeamIssueParams struct {
	Title          sql.NullString `json:"title"`
	Description    sql.NullString `json:"description"`
	Status         sql.NullString `json:"status"`
	AssigneeType   sql.NullString `json:"assignee_type"`
	AssigneeBotID  sql.NullString `json:"assignee_bot_id"`
	AssigneeUserID sql.NullString `json:"assignee_user_id"`
	Metadata       sql.NullString `json:"metadata"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateTeamIssue(ctx context.Context, arg UpdateTeamIssueParams) (TeamIssue, error) {
	row := q.db.QueryRowContext(ctx, updateTeamIssue,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeType,
		arg.AssigneeBotID,
		arg.AssigneeUserID,
		arg.Metadata,
		arg.ID,
	)
	var i TeamIssue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeType,
		&i.AssigneeBotID,
		&i.AssigneeUserID,
		&i.CreatedByType,
		&i.CreatedByBotID,
		&i.CreatedByUserID,
		&i.ParentIssueID,
		&i.Metadata,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
