// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAgentTeamMember = `-- name: AddAgentTeamMember :one
INSERT INTO agent_team_members (team_id, member_type, bot_id, user_id, role, instructions, metadata)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, team_id, member_type, bot_id, user_id, role, instructions, metadata, created_at, updated_at
`

type AddAgentTeamMemberParams struct {
	TeamID       pgtype.UUID `json:"team_id"`
	MemberType   string      `json:"member_type"`
	BotID        pgtype.UUID `json:"bot_id"`
	UserID       pgtype.UUID `json:"user_id"`
	Role         string      `json:"role"`
	Instructions string      `json:"instructions"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) AddAgentTeamMember(ctx context.Context, arg AddAgentTeamMemberParams) (AgentTeamMember, error) {
	row := q.db.QueryRow(ctx, addAgentTeamMember,
		arg.TeamID,
		arg.MemberType,
		arg.BotID,
		arg.UserID,
		arg.Role,
		arg.Instructions,
		arg.Metadata,
	)
	var i AgentTeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MemberType,
		&i.BotID,
		&i.UserID,
		&i.Role,
		&i.Instructions,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveAgentTeam = `-- name: ArchiveAgentTeam :one
UPDATE agent_teams SET archived_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, owner_user_id, name, description, shared_dir_name, instructions, metadata, archived_at, created_at, updated_at
`

func (q *Queries) ArchiveAgentTeam(ctx context.Context, id pgtype.UUID) (AgentTeam, error) {
	row := q.db.QueryRow(ctx, archiveAgentTeam, id)
	var i AgentTeam
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.SharedDirName,
		&i.Instructions,
		&i.Metadata,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentTeam = `-- name: CreateAgentTeam :one
INSERT INTO agent_teams (owner_user_id, name, description, shared_dir_name, instructions, metadata)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, owner_user_id, name, description, shared_dir_name, instructions, metadata, archived_at, created_at, updated_at
`

type CreateAgentTeamParams struct {
	OwnerUserID   pgtype.UUID `json:"owner_user_id"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	SharedDirName string      `json:"shared_dir_name"`
	Instructions  string      `json:"instructions"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateAgentTeam(ctx context.Context, arg CreateAgentTeamParams) (AgentTeam, error) {
	row := q.db.QueryRow(ctx, createAgentTeam,
		arg.OwnerUserID,
		arg.Name,
		arg.Description,
		arg.SharedDirName,
		arg.Instructions,
		arg.Metadata,
	)
	var i AgentTeam
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.SharedDirName,
		&i.Instructions,
		&i.Metadata,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentTeam = `-- name: DeleteAgentTeam :exec
DELETE FROM agent_teams WHERE id = $1
`

func (q *Queries) DeleteAgentTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentTeam, id)
	return err
}

const deleteAgentTeamMember = `-- name: DeleteAgentTeamMember :exec
DELETE FROM agent_team_members WHERE id = $1
`

func (q *Queries) DeleteAgentTeamMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentTeamMember, id)
	return err
}

const getAgentTeam = `-- name: GetAgentTeam :one
SELECT id, owner_user_id, name, description, shared_dir_name, instructions, metadata, archived_at, created_at, updated_at FROM agent_teams WHERE id = $1
`

func (q *Queries) GetAgentTeam(ctx context.Context, id pgtype.UUID) (AgentTeam, error) {
	row := q.db.QueryRow(ctx, getAgentTeam, id)
	var i AgentTeam
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.SharedDirName,
		&i.Instructions,
		&i.Metadata,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTeamForOwner = `-- name: GetAgentTeamForOwner :one
SELECT id, owner_user_id, name, description, shared_dir_name, instructions, metadata, archived_at, created_at, updated_at FROM agent_teams
WHERE id = $1 AND owner_user_id = $2
`

type GetAgentTeamForOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) GetAgentTeamForOwner(ctx context.Context, arg GetAgentTeamForOwnerParams) (AgentTeam, error) {
	row := q.db.QueryRow(ctx, getAgentTeamForOwner, arg.ID, arg.OwnerUserID)
	var i AgentTeam
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.SharedDirName,
		&i.Instructions,
		&i.Metadata,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTeamMember = `-- name: GetAgentTeamMember :one
SELECT
  m.id, m.team_id, m.member_type, m.bot_id, m.user_id,
  m.role, m.instructions, m.metadata, m.created_at, m.updated_at,
  COALESCE(b.display_name, u.display_name, '')::text AS resolved_display_name
FROM agent_team_members m
LEFT JOIN bots b ON m.bot_id = b.id
LEFT JOIN users u ON m.user_id = u.id
WHERE m.id = $1
`

type GetAgentTeamMemberRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TeamID              pgtype.UUID        `json:"team_id"`
	MemberType          string             `json:"member_type"`
	BotID               pgtype.UUID        `json:"bot_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Role                string             `json:"role"`
	Instructions        string             `json:"instructions"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ResolvedDisplayName string             `json:"resolved_display_name"`
}

func (q *Queries) GetAgentTeamMember(ctx context.Context, id pgtype.UUID) (GetAgentTeamMemberRow, error) {
	row := q.db.QueryRow(ctx, getAgentTeamMember, id)
	var i GetAgentTeamMemberRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MemberType,
		&i.BotID,
		&i.UserID,
		&i.Role,
		&i.Instructions,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedDisplayName,
	)
	return i, err
}

const getAgentTeamMemberByBot = `-- name: GetAgentTeamMemberByBot :one
SELECT
  m.id, m.team_id, m.member_type, m.bot_id, m.user_id,
  m.role, m.instructions, m.metadata, m.created_at, m.updated_at,
  COALESCE(b.display_name, '')::text AS resolved_display_name
FROM agent_team_members m
LEFT JOIN bots b ON m.bot_id = b.id
WHERE m.team_id = $1 AND m.bot_id = $2
`

type GetAgentTeamMemberByBotParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	BotID  pgtype.UUID `json:"bot_id"`
}

type GetAgentTeamMemberByBotRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TeamID              pgtype.UUID        `json:"team_id"`
	MemberType          string             `json:"member_type"`
	BotID               pgtype.UUID        `json:"bot_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Role                string             `json:"role"`
	Instructions        string             `json:"instructions"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ResolvedDisplayName string             `json:"resolved_display_name"`
}

func (q *Queries) GetAgentTeamMemberByBot(ctx context.Context, arg GetAgentTeamMemberByBotParams) (GetAgentTeamMemberByBotRow, error) {
	row := q.db.QueryRow(ctx, getAgentTeamMemberByBot, arg.TeamID, arg.BotID)
	var i GetAgentTeamMemberByBotRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MemberType,
		&i.BotID,
		&i.UserID,
		&i.Role,
		&i.Instructions,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedDisplayName,
	)
	return i, err
}

const getAgentTeamMemberByUser = `-- name: GetAgentTeamMemberByUser :one
SELECT
  m.id, m.team_id, m.member_type, m.bot_id, m.user_id,
  m.role, m.instructions, m.metadata, m.created_at, m.updated_at,
  COALESCE(u.display_name, '')::text AS resolved_display_name
FROM agent_team_members m
LEFT JOIN users u ON m.user_id = u.id
WHERE m.team_id = $1 AND m.user_id = $2
`

type GetAgentTeamMemberByUserParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetAgentTeamMemberByUserRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TeamID              pgtype.UUID        `json:"team_id"`
	MemberType          string             `json:"member_type"`
	BotID               pgtype.UUID        `json:"bot_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Role                string             `json:"role"`
	Instructions        string             `json:"instructions"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ResolvedDisplayName string             `json:"resolved_display_name"`
}

func (q *Queries) GetAgentTeamMemberByUser(ctx context.Context, arg GetAgentTeamMemberByUserParams) (GetAgentTeamMemberByUserRow, error) {
	row := q.db.QueryRow(ctx, getAgentTeamMemberByUser, arg.TeamID, arg.UserID)
	var i GetAgentTeamMemberByUserRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MemberType,
		&i.BotID,
		&i.UserID,
		&i.Role,
		&i.Instructions,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedDisplayName,
	)
	return i, err
}

const listAgentTeamMembers = `-- name: ListAgentTeamMembers :many
SELECT
  m.id, m.team_id, m.member_type, m.bot_id, m.user_id,
  m.role, m.instructions, m.metadata, m.created_at, m.updated_at,
  COALESCE(b.display_name, u.display_name, '')::text AS resolved_display_name
FROM agent_team_members m
LEFT JOIN bots b ON m.bot_id = b.id
LEFT JOIN users u ON m.user_id = u.id
WHERE m.team_id = $1
ORDER BY m.created_at ASC
`

type ListAgentTeamMembersRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TeamID              pgtype.UUID        `json:"team_id"`
	MemberType          string             `json:"member_type"`
	BotID               pgtype.UUID        `json:"bot_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Role                string             `json:"role"`
	Instructions        string             `json:"instructions"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ResolvedDisplayName string             `json:"resolved_display_name"`
}

func (q *Queries) ListAgentTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListAgentTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listAgentTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentTeamMembersRow
	for rows.Next() {
		var i ListAgentTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.MemberType,
			&i.BotID,
			&i.UserID,
			&i.Role,
			&i.Instructions,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTeamsByOwner = `-- name: ListAgentTeamsByOwner :many
SELECT id, owner_user_id, name, description, shared_dir_name, instructions, metadata, archived_at, created_at, updated_at FROM agent_teams
WHERE owner_user_id = $1
  AND archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAgentTeamsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]AgentTeam, error) {
	rows, err := q.db.Query(ctx, listAgentTeamsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTeam
	for rows.Next() {
		var i AgentTeam
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.SharedDirName,
			&i.Instructions,
			&i.Metadata,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTeamsForBot = `-- name: ListAgentTeamsForBot :many
SELECT t.id, t.owner_user_id, t.name, t.description, t.shared_dir_name, t.instructions, t.metadata, t.archived_at, t.created_at, t.updated_at FROM agent_teams t
JOIN agent_team_members m ON m.team_id = t.id
WHERE m.bot_id = $1
  AND t.archived_at IS NULL
ORDER BY t.created_at DESC
`

func (q *Queries) ListAgentTeamsForBot(ctx context.Context, botID pgtype.UUID) ([]AgentTeam, error) {
	rows, err := q.db.Query(ctx, listAgentTeamsForBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTeam
	for rows.Next() {
		var i AgentTeam
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.SharedDirName,
			&i.Instructions,
			&i.Metadata,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAgentTeamsByOwner = `-- name: ListAllAgentTeamsByOwner :many
SELECT id, owner_user_id, name, description, shared_dir_name, instructions, metadata, archived_at, created_at, updated_at FROM agent_teams
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAllAgentTeamsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]AgentTeam, error) {
	rows, err := q.db.Query(ctx, listAllAgentTeamsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTeam
	for rows.Next() {
		var i AgentTeam
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.SharedDirName,
			&i.Instructions,
			&i.Metadata,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentTeam = `-- name: UpdateAgentTeam :one
UPDATE agent_teams SET
  name = COALESCE($1, name),
  description = COALESCE($2, description),
  shared_dir_name = COALESCE($3, shared_dir_name),
  instructions = COALESCE($4, instructions),
  metadata = COALESCE($5, metadata),
  updated_at = now()
WHERE id = $6
RETURNING id, owner_user_id, name, description, shared_dir_name, instructions, metadata, archived_at, created_at, updated_at
`

type UpdateAgentTeamParams struct {
	Name          pgtype.Text `json:"name"`
	Description   pgtype.Text `json:"description"`
	SharedDirName pgtype.Text `json:"shared_dir_name"`
	Instructions  pgtype.Text `json:"instructions"`
	Metadata      []byte      `json:"metadata"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentTeam(ctx context.Context, arg UpdateAgentTeamParams) (AgentTeam, error) {
	row := q.db.QueryRow(ctx, updateAgentTeam,
		arg.Name,
		arg.Description,
		arg.SharedDirName,
		arg.Instructions,
		arg.Metadata,
		arg.ID,
	)
	var i AgentTeam
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.SharedDirName,
		&i.Instructions,
		&i.Metadata,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentTeamMember = `-- name: UpdateAgentTeamMember :one
UPDATE agent_team_members SET
  role = COALESCE($1, role),
  instructions = COALESCE($2, instructions),
  metadata = COALESCE($3, metadata),
  updated_at = now()
WHERE id = $4
RETURNING id, team_id, member_type, bot_id, user_id, role, instructions, metadata, created_at, updated_at
`

type UpdateAgentTeamMemberParams struct {
	Role         pgtype.Text `json:"role"`
	Instructions pgtype.Text `json:"instructions"`
	Metadata     []byte      `json:"metadata"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentTeamMember(ctx context.Context, arg UpdateAgentTeamMemberParams) (AgentTeamMember, error) {
	row := q.db.QueryRow(ctx, updateAgentTeamMember,
		arg.Role,
		arg.Instructions,
		arg.Metadata,
		arg.ID,
	)
	var i AgentTeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MemberType,
		&i.BotID,
		&i.UserID,
		&i.Role,
		&i.Instructions,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
