// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_file_locks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTeamFileLock = `-- name: AcquireTeamFileLock :one
INSERT INTO team_file_locks (
  team_id, path, scope, owner_type, owner_bot_id, owner_user_id,
  issue_id, session_id, handoff_id, expires_at, metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
ON CONFLICT (team_id, path, scope) DO NOTHING
RETURNING id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata
`

type AcquireTeamFileLockParams struct {
	TeamID      pgtype.UUID        `json:"team_id"`
	Path        string             `json:"path"`
	Scope       string             `json:"scope"`
	OwnerType   string             `json:"owner_type"`
	OwnerBotID  pgtype.UUID        `json:"owner_bot_id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	IssueID     pgtype.UUID        `json:"issue_id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	HandoffID   pgtype.UUID        `json:"handoff_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) AcquireTeamFileLock(ctx context.Context, arg AcquireTeamFileLockParams) (TeamFileLock, error) {
	row := q.db.QueryRow(ctx, acquireTeamFileLock,
		arg.TeamID,
		arg.Path,
		arg.Scope,
		arg.OwnerType,
		arg.OwnerBotID,
		arg.OwnerUserID,
		arg.IssueID,
		arg.SessionID,
		arg.HandoffID,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i TeamFileLock
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.Scope,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerUserID,
		&i.IssueID,
		&i.SessionID,
		&i.HandoffID,
		&i.AcquiredAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const getTeamFileLock = `-- name: GetTeamFileLock :one
SELECT id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata FROM team_file_locks
WHERE team_id = $1 AND path = $2 AND scope = $3
`

type GetTeamFileLockParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	Path   string      `json:"path"`
	Scope  string      `json:"scope"`
}

func (q *Queries) GetTeamFileLock(ctx context.Context, arg GetTeamFileLockParams) (TeamFileLock, error) {
	row := q.db.QueryRow(ctx, getTeamFileLock, arg.TeamID, arg.Path, arg.Scope)
	var i TeamFileLock
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.Scope,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerUserID,
		&i.IssueID,
		&i.SessionID,
		&i.HandoffID,
		&i.AcquiredAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const getTeamFileLockByID = `-- name: GetTeamFileLockByID :one
SELECT id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata FROM team_file_locks WHERE id = $1
`

func (q *Queries) GetTeamFileLockByID(ctx context.Context, id pgtype.UUID) (TeamFileLock, error) {
	row := q.db.QueryRow(ctx, getTeamFileLockByID, id)
	var i TeamFileLock
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.Scope,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerUserID,
		&i.IssueID,
		&i.SessionID,
		&i.HandoffID,
		&i.AcquiredAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const listActiveTeamFileLocks = `-- name: ListActiveTeamFileLocks :many
SELECT id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata FROM team_file_locks
WHERE team_id = $1
  AND expires_at > now()
ORDER BY acquired_at DESC
`

func (q *Queries) ListActiveTeamFileLocks(ctx context.Context, teamID pgtype.UUID) ([]TeamFileLock, error) {
	rows, err := q.db.Query(ctx, listActiveTeamFileLocks, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamFileLock
	for rows.Next() {
		var i TeamFileLock
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Path,
			&i.Scope,
			&i.OwnerType,
			&i.OwnerBotID,
			&i.OwnerUserID,
			&i.IssueID,
			&i.SessionID,
			&i.HandoffID,
			&i.AcquiredAt,
			&i.RefreshedAt,
			&i.ExpiresAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamFileLocks = `-- name: ListTeamFileLocks :many
SELECT id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata FROM team_file_locks
WHERE team_id = $1
ORDER BY acquired_at DESC
`

func (q *Queries) ListTeamFileLocks(ctx context.Context, teamID pgtype.UUID) ([]TeamFileLock, error) {
	rows, err := q.db.Query(ctx, listTeamFileLocks, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamFileLock
	for rows.Next() {
		var i TeamFileLock
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Path,
			&i.Scope,
			&i.OwnerType,
			&i.OwnerBotID,
			&i.OwnerUserID,
			&i.IssueID,
			&i.SessionID,
			&i.HandoffID,
			&i.AcquiredAt,
			&i.RefreshedAt,
			&i.ExpiresAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTeamFileLock = `-- name: RefreshTeamFileLock :one
UPDATE team_file_locks SET
  refreshed_at = now(),
  expires_at = $1
WHERE id = $2
RETURNING id, team_id, path, scope, owner_type, owner_bot_id, owner_user_id, issue_id, session_id, handoff_id, acquired_at, refreshed_at, expires_at, metadata
`

type RefreshTeamFileLockParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RefreshTeamFileLock(ctx context.Context, arg RefreshTeamFileLockParams) (TeamFileLock, error) {
	row := q.db.QueryRow(ctx, refreshTeamFileLock, arg.ExpiresAt, arg.ID)
	var i TeamFileLock
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Path,
		&i.Scope,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerUserID,
		&i.IssueID,
		&i.SessionID,
		&i.HandoffID,
		&i.AcquiredAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const releaseExpiredTeamFileLocks = `-- name: ReleaseExpiredTeamFileLocks :exec
DELETE FROM team_file_locks
WHERE expires_at <= now()
`

func (q *Queries) ReleaseExpiredTeamFileLocks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, releaseExpiredTeamFileLocks)
	return err
}

const releaseTeamFileLock = `-- name: ReleaseTeamFileLock :exec
DELETE FROM team_file_locks WHERE id = $1
`

func (q *Queries) ReleaseTeamFileLock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseTeamFileLock, id)
	return err
}
